<template><h1 id="examples" tabindex="-1"><a class="header-anchor" href="#examples" aria-hidden="true">#</a> Examples</h1>
<h3 id="gif" tabindex="-1"><a class="header-anchor" href="#gif" aria-hidden="true">#</a> GIF</h3>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> WeebyAPI <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'weeby-js'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> weeby <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">WeebyAPI</span><span class="token punctuation">(</span><span class="token string">'YOUR_TOKEN'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token keyword">const</span> gif <span class="token operator">=</span> <span class="token keyword">await</span> weeby<span class="token punctuation">.</span>gif<span class="token punctuation">.</span><span class="token function">fetch</span><span class="token punctuation">(</span><span class="token string">'pat'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>gif<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// -> https://cdn.weebyapi.xyz/img/gif/pat/13.gif</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div><h3 id="generator" tabindex="-1"><a class="header-anchor" href="#generator" aria-hidden="true">#</a> Generator</h3>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> WeebyAPI <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'weeby-js'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> weeby <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">WeebyAPI</span><span class="token punctuation">(</span><span class="token string">'YOUR_TOKEN'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token keyword">const</span> image <span class="token operator">=</span> <span class="token keyword">await</span> weeby<span class="token punctuation">.</span>generators<span class="token punctuation">.</span><span class="token function">oneImage</span><span class="token punctuation">(</span><span class="token punctuation">{</span> type<span class="token operator">:</span> <span class="token string">'3000years'</span><span class="token punctuation">,</span> image<span class="token operator">:</span> <span class="token string">'https://i.imgur.com/qgKvcQv.png'</span> <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
message<span class="token punctuation">.</span>channel<span class="token punctuation">.</span><span class="token function">send</span><span class="token punctuation">(</span><span class="token punctuation">{</span> files<span class="token operator">:</span> <span class="token punctuation">[</span><span class="token punctuation">{</span> attachment<span class="token operator">:</span> image <span class="token punctuation">}</span><span class="token punctuation">]</span> <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// -> Image Buffer</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div><h3 id="custom" tabindex="-1"><a class="header-anchor" href="#custom" aria-hidden="true">#</a> Custom</h3>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> WeebyAPI <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'weeby-js'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> weeby <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">WeebyAPI</span><span class="token punctuation">(</span><span class="token string">'YOUR_TOKEN'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token keyword">const</span> image <span class="token operator">=</span> <span class="token keyword">await</span> weeby<span class="token punctuation">.</span>custom<span class="token punctuation">.</span><span class="token function">greeting</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
	icon<span class="token operator">:</span> <span class="token string">'https://i.imgur.com/qgKvcQv.png'</span><span class="token punctuation">,</span>
	background<span class="token operator">:</span> <span class="token string">'https://i.imgur.com/ENbvdWD.png'</span><span class="token punctuation">,</span>
	greet<span class="token operator">:</span> <span class="token string">'Welcome'</span><span class="token punctuation">,</span>
	name<span class="token operator">:</span> <span class="token string">'Nate'</span><span class="token punctuation">,</span>
	message<span class="token operator">:</span> <span class="token string">'Hello and Welcome!'</span><span class="token punctuation">,</span>
	greetHex<span class="token operator">:</span> <span class="token string">'E881D1'</span><span class="token punctuation">,</span>
	messageHex<span class="token operator">:</span> <span class="token string">'76d6ff'</span><span class="token punctuation">,</span>
	circleHex<span class="token operator">:</span> <span class="token string">'6b6d75'</span><span class="token punctuation">,</span>
	nameHex<span class="token operator">:</span> <span class="token string">'e889e0'</span><span class="token punctuation">,</span>
	font<span class="token operator">:</span> <span class="token string">'riffic'</span><span class="token punctuation">,</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

message<span class="token punctuation">.</span>channel<span class="token punctuation">.</span><span class="token function">send</span><span class="token punctuation">(</span><span class="token punctuation">{</span> files<span class="token operator">:</span> <span class="token punctuation">[</span><span class="token punctuation">{</span> attachment<span class="token operator">:</span> image <span class="token punctuation">}</span><span class="token punctuation">]</span> <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// -> Image Buffer</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br></div></div></template>
